sudo: enabled
language: node_js
node_js:
- '8'
before_install:
- yarn global add typescript tslint
cache: yarn
install:
- yarn
script:
- tslint ./src/**/*.ts
- yarn test:coverage
deploy:
  provider: heroku
  api_key:
    secure: t3+EH0GR3N+s4NzERBgU0ez7acRKDuNRhwymQAp036Cxp7QWZUxWLt12bY6cR3XKo1OXAT+Woi4Br8/CeBFp6srnW9ecHu9ixT/QxJFNR8P6yO247h4yagT2TnVB/6m4M7KVepPsTGgHIClc31qk2AlwqIIcqMthRg43wvPzSZbADQsaw9JNCTX5zU3z00PK9l7iZsvNsCDKCZBiSFrs00j/KakyE6zPbbOdWradNmSzz3fXE1t6oivnggs01SkBbwdTfh70ARnD5RqFCm9HlfqThCsmZxcylCts1EA+n+wuYR5U4vA4hhhE72xvb43glzA9OxrN9nBeokicvYPzvqu2oReiatyvhNNXZqXtPMlpwSZEf8TW2Uqj7vM/mETXDK/LOSTBIaeo/UuKGYJFLCerdkWi+xGwiCGJJ9F+d6TI9nPXKXy6GObDZRzFPyxaO3KTo6Qy2TNTfUh/+tYYSrap4M7GZUyNJgpzwLRaOt4sd6tnKBC/HrV7ix/aLHqKK3vLV0K/uwNJyYk+U94tFr5OaIUSbLrCOA/VButv1vL26sU2S/y2ei/OPfWyEItXoeB3e9si5XytuJnu09fbQdPNgzx+xiQ4hW/QsIjYzJAQ0OEBPTojlIRt5FV/xxYOBeoO3vuah8sUQFnzEpuVI5rxro/G4ETOaoei6PuBxYA=
  app: carfinderapp
  on:
    repo: CarFinder/CarFinderApi
    branch: dev
